### ISSUE TITLE
Text not showing

### ISSUE THREAD

**Issue by jepperaskdk** [matbloch/electron-flask#1]
Hey, thank you for the template! "HELLO WORLD" does not seem to show, however it does if I access localhost:4040 in my browser.

**Comment by matbloch** [comment]
On what platform are you running it? Try to enable the debug toolback and see what is actually being rendered.
To do so, uncomment line 39 in `main.js`: 
`mainWindow.webContents.openDevTools();`

**Comment by jepperaskdk** [comment]
I think I solved it by a combination of disabling cache in developer tools and by adding some headers from the server.

**Comment by matbloch** [comment]
Glad you could solve it on your own. Sorry for the delayed aswer.
