### ISSUE TITLE
A few bugs found

### ISSUE THREAD

**Issue by blademaster-888** [matbloch/electron-flask#3]
Hi,
 I like what  you're doing :smiley: . When I tried to build it and run it I get the weird error when loading electron . 

1. It loads up the electron.js file into the notepad instead. I recommend you rename electron.js to something like renderer.js so this won't happen.

2. In package.json the commands has got a typo:
"package-python": "pyinstaller -w -F --add-data web_app/templates;templates --add-data web_app/static;static web_app/run_app.py --distpath dist-python",
So all I added was adding /app in the mix like so:

"package-python": "pyinstaller -w -F --add-data web_app/app/templates;templates --add-data web_app/app/static;static web_app/run_app.py --distpath dist-python",

3. When running the app, I get a blank gui screen. Probably due to python not running the script. I haven't found a fix yet and stil looking into it.

Hope that helps.
Cheers.

**Comment by matbloch** [comment]
Thanks a lot for your feedback!
I patched the invalid paths and also renamed electron.js to avoid confusion.

**About point 3**: Could you resolve the issue? Could it be that the webserver didn't start up yet when the rendrer was loaded? For debugging, you can enable the debug toolback and try to refresh the page.

**Comment by NamasteJasutin** [comment]
Hi,

I've been working with this app and it runs fine on the host machine I build this on, but when deploying, we don't see the Flask Server start up.
I've verified this by installing a clean version of MacOS Catalina in a VirtualBox VM, copied the files over and run the app.
Same behaviour, so I started digging deeper.
Opening the run_app script in the Apps Package Contents > Contents > Resources > app - dist-python > run_app (I tried both the shell file and the .app, the Shell file runs in a terminal and hands over the error):
```
Traceback (most recent call last):
  File "run_app.py", line 1, in <module>
  File "/usr/local/Cellar/pyinstaller/3.6_1/libexec/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "app/__init__.py", line1, in <module>
ModuleNotFoundError: No module named 'flask'
[1414] Failed to execute script run_app
```

I'm not well known on PyInstaller and deploying with modules.

**Comment by matbloch** [comment]
> 
> 
> Hi,
> 
> I've been working with this app and it runs fine on the host machine I build this on, but when deploying, we don't see the Flask Server start up.
> I've verified this by installing a clean version of MacOS Catalina in a VirtualBox VM, copied the files over and run the app.
> Same behaviour, so I started digging deeper.
> Opening the run_app script in the Apps Package Contents > Contents > Resources > app - dist-python > run_app (I tried both the shell file and the .app, the Shell file runs in a terminal and hands over the error):
> 
> ```
> Traceback (most recent call last):
>   File "run_app.py", line 1, in <module>
>   File "/usr/local/Cellar/pyinstaller/3.6_1/libexec/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
>   File "app/__init__.py", line1, in <module>
> ModuleNotFoundError: No module named 'flask'
> [1414] Failed to execute script run_app
> ```
> 
> I'm not well known on PyInstaller and deploying with modules.

Thank you for reporting this issue. Pyinstaller searches the source code for `import` statements to collect the dependencies. I have a look at it as soon as time allows.

**Comment by matbloch** [comment]
Please checkout the latest version. There was a bug where Pyinstaller would not be able to find the Flask configuration. This mostly likely causes the issues you mentioned. This is now resolved.
