### ISSUE TITLE
Packaging doesn't work for linux

### ISSUE THREAD

**Issue by dboun** [matbloch/electron-flask#6]
Unless ; is replaced with : in package.json (at the pyinstaller command) (because : is the linux file separator)

Cheers

**Comment by cgsops** [comment]
and how run for linux?, because I ran for linux the flask not running by it self

**Comment by matbloch** [comment]
The path separators are now dynamically resolved when calling `npm run package`.

@cgsops Please open a separate issue if the problem persists
