### ISSUE TITLE
Electron app does not change

### ISSUE THREAD

**Issue by ConnyCola** [matbloch/electron-flask#7]
Hi, I am sorry if it is me not understanding how the packaging is working, but I have the issue that the page in the electron app is not changing but if I run just the python app and check the page in the browser everything works. 
So starting it with 'python3.9 web_app/run_app.py' and checking in chrome I see the changes which I made to index.html.
If i now start it with './node_modules/.bin/electron .' the application starts app only shows Hello World but non of my changes. 
If I try to package it with npm run package I get an electron.app file but it also shows only the Hello World but non of my changes. 
Am I doing something wrong?

**Comment by matbloch** [comment]
Sorry for the late reply. It's a bit difficult to identify the problem without a sample but a good start is to check if it's a caching problem. Could you please try to reload the page that is rendered through electron (enable the development bar through line 87 in `renderer.js` or register a shortcut, e.g. like this: https://github.com/electron/electron/issues/11895)?

**Comment by matbloch** [comment]
I'm closing this issue. If you experience any problems, please re-open it.
